source "git@github.com:CocoaPods/Specs.git"
platform :ios, '15.0'

workspace 'Sample'

# чтобы работал Swift
use_frameworks!

pod 'SnapKit'
pod 'FlexLayout', :path => '../'

project_path = Dir.entries('.').find { |e| e.end_with? ".xcodeproj" }
project = Xcodeproj::Project.open(project_path)

project.targets.each do |target|
  puts "target \"#{target.name}\""
  target target.name
end
